### ISSUE TITLE
tmp dir cleanup

### ISSUE THREAD

**Issue by alex-wilmer** [Windscribe/uBlock#3]
```
~/Projects/windscribe/ext⚡️yarn start
yarn run v1.9.4
$ NODE_PATH=src/common react-scripts start
ℹ info Building manifest for target: dev
⚠ warn Ubo source missing
ℹ info Pulling and building ubo. This may take a few minutes
✖ error Error: Command failed: git clone https://github.com/Windscribe/uBlock .
  fatal: unable to get current working directory: No such file or directory

  at ChildProcess.exithandler (child_process.js:273:12)
  at ChildProcess.emit (events.js:180:13)
  at maybeClose (internal/child_process.js:936:16)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
```

didn't realize until wayyyy later that this was a leftover tmp dir problem.

yes I know it's the wrong repo but I didn't want to forget about this, or use jira

**Comment by jbarzegar** [comment]
Not related to this project

**Comment by alex-wilmer** [comment]
> Not related to this project
yes I specifically mentioned that in my comment. hopefully one day Windscribe will be so ubiquitous that we'll need to hire a full time issue-closer, until then, this is my workspace as much as it is yours.

I wouldn't mind if you closed it and addressed it, but just outright closing it is not appropriate.

All good now, just keep in mind for next time.
